// <auto-generated />
using API_Farm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Farm.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240918123503_AddDataIntoAnimalTypes")]
    partial class AddDataIntoAnimalTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_Farm.Models.AnimalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("animal_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "vertebrados de sangre caliente con pelo o pelaje.",
                            Name = "mamífero"
                        },
                        new
                        {
                            Id = 2,
                            Description = "vertebrados emplumados y alados capaces de volar.",
                            Name = "ave"
                        },
                        new
                        {
                            Id = 3,
                            Description = "vertebrados de sangre fría con escamas.",
                            Name = "reptil"
                        },
                        new
                        {
                            Id = 4,
                            Description = "vertebrados de sangre fría que pasan parte de su vida en el agua y parte en tierra.",
                            Name = "anfibio"
                        },
                        new
                        {
                            Id = 5,
                            Description = "vertebrados acuáticos con branquias, aletas y escamas.",
                            Name = "pez"
                        },
                        new
                        {
                            Id = 6,
                            Description = "animales sin columna vertebral, incluyendo insectos, arañas y moluscos.",
                            Name = "invertebrado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
